### ISSUE TITLE
OAuth2 Redirect URI 

### ISSUE THREAD

**Issue by d0pamin** [jgauth/MMM-GoogleTasks#21]
Hi,
I followed the steps to activate the google task api. But I have some problems with the redirect uri, when executing '`node authenticate.js`' .
What is it supposed to be? Right now its http://localhost. 
As a result my webbrowser has no access to the returned url witch is needed to authorize the app.

Best,
Max

**Comment by m4tsu0** [comment]
Hello, I see you closed the issue. Can you please share how you fixed the problem? Ive been struggling for two days with authentication.

**Comment by d0pamin** [comment]
Hello,
I closed the Issue, because it was a duplicate to https://github.com/jgauth/MMM-GoogleTasks/issues/17.

The Solution is to 

>  Copy everything after ...code= in the url. - [amarko87](https://github.com/amarko87)

The Url, at least in my case, was pretty long - but you had to copy everything after code= and paste it to the terminal.
